ARG BCC_VERSION=v0.28.0

FROM dataucon/ubuntu-bcc:${BCC_VERSION}

RUN apt-get update && apt-get install -y tini \
    && rm -rf /var/lib/apt/lists/*

RUN pip install jupyterlab

COPY . /duetector
RUN pip install -e /duetector --no-cache-dir


ARG APPLICATION_UID=9999
ARG APPLICATION_GID=9999
RUN addgroup --system --gid ${APPLICATION_GID} application && \
    adduser --system --gid ${APPLICATION_GID} --home /home/application --uid ${APPLICATION_UID} --disabled-password application && \
    usermod -s /bin/bash application

COPY docker/start.sh /start.sh
RUN chmod +x /start.sh

CMD [ "/sbin/tini", "--" ]
ENTRYPOINT [ "/start.sh" ]

# docker build -t duetector:dev -f docker/Dockerfile.dev .

# Current kernel build with CONFIG_IKHEADERS=m
# docker run -it --rm -p 8888:8888 --cap-add=sys_admin -v /sys/kernel/kheaders.tar.xz:/sys/kernel/kheaders.tar.xz -v /sys/kernel/debug:/sys/kernel/debug duetector:dev

# Currnet kernel installed with headers
# docker run -it --rm -p 8888:8888 --cap-add=sys_admin -v /usr/lib/modules:/usr/lib/modules -v /sys/kernel/debug:/sys/kernel/debug duetector:dev
